### ISSUE TITLE
Providers should have a lint workflow/step on the `docs` folder content

### ISSUE THREAD

**Issue by ringods** [pulumi/ci-mgmt#1100]
When a resource provider package contains a `docs` folder, the content should be linted. This workflow/step should pass before a release can happen.

When the content is not correct, these files are copied over to the registry for publishing and it fails the publishing there without any feedback loop back to the source.

Example: MongoDB Atlas is currently at v3.20.1. All versions from v3.18.1 failed publishing so far:

* v3.18.1: https://github.com/pulumi/registry/pull/5463
* v3.19.0: https://github.com/pulumi/registry/pull/5489
* v3.19.1: https://github.com/pulumi/registry/pull/5509
* v3.20.0: https://github.com/pulumi/registry/pull/5639
* v3.20.1: https://github.com/pulumi/registry/pull/5665

**Comment by ringods** [comment]
More cases:

* https://github.com/pulumi/registry/pull/5620
* https://github.com/pulumi/registry/pull/5374

**Comment by guineveresaenger** [comment]
Update here:

After talking to the team, we have decided to not take this ticket, at least not in this scope. 

Rather, we will follow existing policy and not lint autogenerated files in the registry, since we do not control the inputs here.

Once we finalize https://github.com/pulumi/registry/issues/3883, we may reconsider adding a lint step, but only on providers that continue to hand-author their installation docs.

Currently we feel that relaxing/disabling the linting rules as in https://github.com/pulumi/registry/issues/3883 is sufficient here.

Closing this issue as a partial wontfix.
