### ISSUE TITLE
Allow providers to perform major version updates without ci-mgmt PRs

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/ci-mgmt#318]
Updating a major version in a provider currently requires four or more pull requests, as shown with recent updates to Keycloak.

See: 
- https://github.com/pulumi/pulumi-keycloak/pull/162
- https://github.com/pulumi/pulumi-keycloak/pull/163
- https://github.com/pulumi/ci-mgmt/pull/315
- https://github.com/pulumi/pulumi-keycloak/pull/164

Even major version updates should follow a normal release process for a software project: a code change followed by a release ceremony. For our providers, this would be a pull request and a `@release-bot` automation.

A pull request was made to Keycloak to demonstrate changes to ci-mgmt outputs that we'd have to make to support this:
- https://github.com/pulumi/pulumi-keycloak/pull/165

If these changes were in place, three of the four pull requests would not have been needed to update Keycloak to v5.

**Comment by t0yv0** [comment]
The PR has been stalling a bit but I want to log some new findings/suggestions based on going through the TLS major version change.

One thing we should do is make the Makefile read VERSION_PREFIX from a file in the repository, to pass to pulumictl. Note that it's somehow a pain in Makefile to pass env vars to $(shell) sub-commands so that might need to be rewritten.. The requirement is that a maintainer that wants to initiate a new major version upgrade, edits the repo to indicate the new major version but does not edit the ci-mgmt controlled Makefile. Then this constraints version selection to start picking up new, say 5.x.x. versions. Which actually changes how sdk/go generated files look like.

**Comment by AaronFriel** [comment]
With the Keycloak PR above, the major version was completely removed from the Makefile. That simplified things quite a lot. I'd need to look to see how the VERSION_PREFIX was calculated, but I think pulumictl will pick it up from the git tag on release builds.

**Comment by t0yv0** [comment]
Also as regards to the PR in https://github.com/pulumi/ci-mgmt/pull/319 - the idea to remove "/v5" completely from examples/ code is very clever, but costs making the examples bit less copy-paste able. I'm on the fence there if the tradeoff's worth it. For an alt approach here's a quickie tool that does `gofmt -r` and `go mod edit` changes:

https://github.com/pulumi/upgrade-provider/pull/9

It can also presumably scan README.md with regexes to update those, but maybe we should just edit out versioned references from the READMEs..

A version of this tool can be used as a read-only lint check to make sure the repo is consistent in terms of the major version.

**Comment by t0yv0** [comment]
Yeah Keycloak still doing `VERSION := $(shell pulumictl get version)` that's going to compute the old (say v4.x.x) version uses you already have the new (say 5.x.x) tag in history, which is a pain for the upgrade PRs.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-tls/pull/190 runs tests on new version so there's no need to do the "disable/enable" test dance. I think that's really compelling.

**Comment by AaronFriel** [comment]
We can decouple the Keycloak PR's makefile changes from the examples changes - we don't need to ship both.

**Comment by iwahbe** [comment]
Fixed by moving the source of truth about a provider to the provider's repo: `.ci-mgmt.yaml`.
