### ISSUE TITLE
Modularize bridged provider test setup for re-use

### ISSUE THREAD

**Issue by thomas11** [pulumi/ci-mgmt#752]
pulumi/pulumi-aws#3074 uses the extension point `extraTests` in `.ci-mgmt.yaml` to add additional tests. That works great, but it required copy-pasting ~17 workflow steps verbatim to get everything set up so tests could run (check out repo, install dependencies, etc.). If this standard setup was extracted into one or more actions similar to, e.g., [install](https://github.com/pulumi/pulumi-azure-native/tree/master/.github/actions/install) in azure-native, it could simply be re-used.

**Comment by blampe** [comment]
We consolidated the test workflow (https://github.com/pulumi/ci-mgmt/pull/1214), which would make it much more straightforward to run some additional steps. However ultimately `extraTests` has been removed from AWS because all of these workflows were more appropriately formulated as standard unit or integration tests.

* https://github.com/pulumi/pulumi-aws/pull/4918
* https://github.com/pulumi/pulumi-aws/pull/4917
* https://github.com/pulumi/pulumi-aws/pull/4909

The custom workflows were slow, hard to maintain, and introduced subtle bugs.
